CREATE TABLE IF NOT EXISTS LichSuLamBai (
  MaLichSu BIGINT NOT NULL AUTO_INCREMENT,
  MaND INT NOT NULL,
  MaChuong INT NOT NULL,
  LanThu INT NOT NULL,
  TongSoCau INT NOT NULL,
  SoCauDung INT NOT NULL DEFAULT 0,
  TyLeDung DECIMAL(5,2) NOT NULL DEFAULT 0,
  Dat BIT NOT NULL DEFAULT 0,
  TrangThai ENUM('IN_PROGRESS', 'SUBMITTED', 'ABANDONED') NOT NULL DEFAULT 'IN_PROGRESS',
  BatDauLuc DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  NopLuc DATETIME NULL,
  PRIMARY KEY (MaLichSu),
  UNIQUE KEY UQ_LichSuLamBai_NguoiDung_Chuong_Lan (MaND, MaChuong, LanThu),
  INDEX IDX_LichSuLamBai_NguoiDung_Chuong (MaND, MaChuong),
  CONSTRAINT FK_LichSuLamBai_NguoiDung FOREIGN KEY (MaND) REFERENCES NguoiDung(MaND),
  CONSTRAINT FK_LichSuLamBai_ChuongHoc FOREIGN KEY (MaChuong) REFERENCES ChuongHoc(MaChuong)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS ChiTietLichSuLamBai (
  MaChiTiet BIGINT NOT NULL AUTO_INCREMENT,
  MaLichSu BIGINT NOT NULL,
  MaCauHoi INT NOT NULL,
  DapAnChon ENUM('A', 'B', 'C', 'D') NULL,
  DapAnDung ENUM('A', 'B', 'C', 'D') NOT NULL,
  Dung BIT NOT NULL DEFAULT 0,
  PRIMARY KEY (MaChiTiet),
  UNIQUE KEY UQ_ChiTietLichSuLamBai_CauHoi (MaLichSu, MaCauHoi),
  CONSTRAINT FK_ChiTietLichSuLamBai_LichSu FOREIGN KEY (MaLichSu)
    REFERENCES LichSuLamBai(MaLichSu) ON DELETE CASCADE,
  CONSTRAINT FK_ChiTietLichSuLamBai_CauHoi FOREIGN KEY (MaCauHoi)
    REFERENCES CauHoiTracNghiem(MaCauHoi)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
