-- Use this migration only when the old article category enum already exists.
ALTER TABLE `BaiViet`
  MODIFY COLUMN `DanhMuc` ENUM(
    'STUDY_TIPS', 'COURSE_NEWS', 'SOFT_SKILLS', 'TECHNICAL',
    'ANNOUNCEMENT', 'SYSTEM_UPDATE', 'PROMOTION', 'NEWS'
  ) NOT NULL DEFAULT 'NEWS';

UPDATE `BaiViet`
SET `DanhMuc` = CASE `DanhMuc`
  WHEN 'COURSE_NEWS' THEN 'NEWS'
  WHEN 'STUDY_TIPS' THEN 'ANNOUNCEMENT'
  WHEN 'SOFT_SKILLS' THEN 'NEWS'
  WHEN 'TECHNICAL' THEN 'SYSTEM_UPDATE'
  ELSE 'NEWS'
END;

ALTER TABLE `BaiViet`
  MODIFY COLUMN `DanhMuc` ENUM('ANNOUNCEMENT', 'SYSTEM_UPDATE', 'PROMOTION', 'NEWS')
  NOT NULL DEFAULT 'NEWS',
  ADD COLUMN `IsPinned` TINYINT(1) NOT NULL DEFAULT 0 AFTER `DanhMuc`;
