function w(pattern: string): RegExp {
  const spaced = pattern.split('').join('[\\s\\-_.@*|#]*');
  return new RegExp(spaced, 'i');
}

export const BAD_WORD_PATTERNS: readonly RegExp[] = Object.freeze([
  w('vl'),
  w('vc'),
  w('vch'),
  w('vãi'),
  w('đái'),
  w('bắc kì'),
  w('bắc kỳ'),
  w('backi'),
  w('chó'),
  w('đụ'),
  w('đéo'),
  w('đcm'),
  w('đmm'),
  w('đm'),
  w('đmcs'),
  w('dm'),           
  w('clm'),
  w('cặc'),
  w('buồi'),
  w('lồn'),
  w('lol'),          
  w('đít'),
  w('địt'),
  w('dit'),
  w('fuck'),
  w('fuk'),
  w('fck'),
  w('shit'),
  w('bitch'),
  w('asshole'),
  w('bastard'),
  w('thằng chó'),
  w('con chó'),
  w('chó chết'),
  w('súc vật'),
  w('ngu'),          
  w('óc chó'),
  w('mặt lồn'),
  w('đầu buồi'),
  w('thối'),         
  w('vô học'),
  w('mày chết'),
  w('cút'),
  w('đồ ngu'),
  w('thằng ngu'),
  w('con ngu'),
  w('óc lợn'),
  w('đần'),
  w('khốn nạn'),
  w('khốn kiếp'),
  w('đồ chó'),
  w('mẹ mày'),
  w('bố mày'),
  /đ[u\*@]+/i,       
  /đ[ụ\*].*mẹ/i,    
  /l[o0][^\w]*[ln]/i, 
  /c[aă][^\w]*[ck]/i, 
  /bu[o0][^\w]*i/i,  
  /f[u\*][^\w]*[ck]/i, 
]);
